/**
 * Generated by anjay_codegen.py on 2022-12-21 09:29:44
 *
 * LwM2M Object: Diagnóstico Wi-Sun
 * ID: 32770, URN: urn:oma:lwm2m:x:32770, Mandatory, Single
 *
 * DLMS Wi-SUN diagnostics - calss_id=96, version 0.
 */
#include <assert.h>
#include <stdbool.h>

#include <anjay/anjay.h>
#include <avsystem/commons/avs_defs.h>
#include <avsystem/commons/avs_memory.h>
#include "def.h"

/**
 * Identificação dispositivo: R, Single, Mandatory
 * type: string, range: N/A, unit: N/A
 * Some description.
 */
#define RID_IDENTIFICA_O_DISPOSITIVO 0

/**
 * Versão do protocolo Wi-SUN: R, Single, Mandatory
 * type: integer, range: N/A, unit: N/A
 * Some description.
 */
#define RID_VERS_O_DO_PROTOCOLO_WI_SUN 1

/**
 * IF - Número de dispositivos físicos conectados: R, Single, Mandatory
 * type: integer, range: N/A, unit: N/A
 * Some description.
 */
#define RID_IF_N_MERO_DE_DISPOSITIVOS_F_SICOS_CONECTADOS 2

/**
 * IF - Endereço do dispositivo físico: R, Single, Mandatory
 * type: string, range: N/A, unit: N/A
 * Some description.
 */
#define RID_IF_ENDERE_O_DO_DISPOSITIVO_F_SICO 3

/**
 * IF - Contador de Pacotes Recebidos para interface: R, Single, Mandatory
 * type: integer, range: N/A, unit: N/A
 * Some description.
 */
#define RID_IF_CONTADOR_DE_PACOTES_RECEBIDOS_PARA_INTERFACE 4

/**
 * IF - Contador de Pacotes Enviados pela interface: R, Single, Mandatory
 * type: integer, range: N/A, unit: N/A
 * Some description.
 */
#define RID_IF_CONTADOR_DE_PACOTES_ENVIADOS_PELA_INTERFACE 5

/**
 * IF - Contador de erro Wi-SUN no envio do pacote: R, Single, Mandatory
 * type: integer, range: N/A, unit: N/A
 * Some description.
 */
#define RID_IF_CONTADOR_DE_ERRO_WI_SUN_NO_ENVIO_DO_PACOTE 6

/**
 * EW - RX Success Count: R, Single, Mandatory
 * type: integer, range: N/A, unit: N/A
 * Some description.
 */
#define RID_EW_RX_SUCCESS_COUNT 7

/**
 * EW - TX Success Count: R, Single, Mandatory
 * type: integer, range: N/A, unit: N/A
 * Some description.
 */
#define RID_EW_TX_SUCCESS_COUNT 8

/**
 * EW - TX FailCount: R, Single, Mandatory
 * type: integer, range: N/A, unit: N/A
 * Some description.
 */
#define RID_EW_TX_FAILCOUNT 9

/**
 * EW - TX Retry Count: R, Single, Mandatory
 * type: integer, range: N/A, unit: N/A
 * Some description.
 */
#define RID_EW_TX_RETRY_COUNT 10

/**
 * EW - RSSI: R, Single, Mandatory
 * type: integer, range: N/A, unit: N/A
 * Some description.
 */
#define RID_EW_RSSI 11

/**
 * EW - Intervalo de Envio: R, Single, Mandatory
 * type: integer, range: N/A, unit: N/A
 * Some description.
 */
#define RID_EW_INTERVALO_DE_ENVIO 12

/**
 * PARENT_IPV6_PREFERRED: R, Single, Mandatory
 * type: string, range: N/A, unit: N/A
 * Some description.
 */
#define RID_PARENT_IPV6_PREFERRED 13

/**
 * PARENT_IPV6_ALTERNATIVE: R, Single, Mandatory
 * type: string, range: N/A, unit: N/A
 * Some description.
 */
#define RID_PARENT_IPV6_ALTERNATIVE 14

/**
 * Time to Connect: R, Single, Mandatory
 * type: integer, range: N/A, unit: N/A
 * Some description.
 */
#define RID_TIME_TO_CONNECT 15

typedef struct diagnostico_wi_sun_object_struct {
    const anjay_dm_object_def_t *def;

    // TODO: object state
} diagnostico_wi_sun_object_t;

static inline diagnostico_wi_sun_object_t *
get_obj(const anjay_dm_object_def_t *const *obj_ptr) {
    assert(obj_ptr);
    return AVS_CONTAINER_OF(obj_ptr, diagnostico_wi_sun_object_t, def);
}

static int list_resources(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_iid_t iid,
                          anjay_dm_resource_list_ctx_t *ctx) {
    (void) anjay;
    (void) obj_ptr;
    (void) iid;

    anjay_dm_emit_res(ctx, RID_IDENTIFICA_O_DISPOSITIVO,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_VERS_O_DO_PROTOCOLO_WI_SUN,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_IF_N_MERO_DE_DISPOSITIVOS_F_SICOS_CONECTADOS,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_IF_ENDERE_O_DO_DISPOSITIVO_F_SICO,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_IF_CONTADOR_DE_PACOTES_RECEBIDOS_PARA_INTERFACE,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_IF_CONTADOR_DE_PACOTES_ENVIADOS_PELA_INTERFACE,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_IF_CONTADOR_DE_ERRO_WI_SUN_NO_ENVIO_DO_PACOTE,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_EW_RX_SUCCESS_COUNT,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_EW_TX_SUCCESS_COUNT,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_EW_TX_FAILCOUNT,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_EW_TX_RETRY_COUNT,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_EW_RSSI,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_EW_INTERVALO_DE_ENVIO,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_PARENT_IPV6_PREFERRED,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_PARENT_IPV6_ALTERNATIVE,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_TIME_TO_CONNECT,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    return 0;
}

static int resource_read(anjay_t *anjay,
                         const anjay_dm_object_def_t *const *obj_ptr,
                         anjay_iid_t iid,
                         anjay_rid_t rid,
                         anjay_riid_t riid,
                         anjay_output_ctx_t *ctx) {
    (void) anjay;
    (void) iid;

    diagnostico_wi_sun_object_t *obj = get_obj(obj_ptr);
    assert(obj);
    assert(iid == 0);

    switch (rid) {
    case RID_IDENTIFICA_O_DISPOSITIVO:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_string(ctx, IDENTIFICA_O_DISPOSITIVO); // TODO

    case RID_VERS_O_DO_PROTOCOLO_WI_SUN:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_string(ctx, VERS_O_DO_PROTOCOLO_WI_SUN); // TODO

    case RID_IF_N_MERO_DE_DISPOSITIVOS_F_SICOS_CONECTADOS:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_i32(ctx, IF_N_MERO_DE_DISPOSITIVOS_F_SICOS_CONECTADOS); // TODO

    case RID_IF_ENDERE_O_DO_DISPOSITIVO_F_SICO:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_string(ctx, IF_ENDERE_O_DO_DISPOSITIVO_F_SICO); // TODO

    case RID_IF_CONTADOR_DE_PACOTES_RECEBIDOS_PARA_INTERFACE:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_i32(ctx, IF_CONTADOR_DE_PACOTES_RECEBIDOS_PARA_INTERFACE); // TODO

    case RID_IF_CONTADOR_DE_PACOTES_ENVIADOS_PELA_INTERFACE:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_i32(ctx, IF_CONTADOR_DE_PACOTES_ENVIADOS_PELA_INTERFACE); // TODO

    case RID_IF_CONTADOR_DE_ERRO_WI_SUN_NO_ENVIO_DO_PACOTE:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_i32(ctx, IF_CONTADOR_DE_ERRO_WI_SUN_NO_ENVIO_DO_PACOTE); // TODO

    case RID_EW_RX_SUCCESS_COUNT:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_i32(ctx, EW_RX_SUCCESS_COUNT); // TODO

    case RID_EW_TX_SUCCESS_COUNT:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_i32(ctx, EW_TX_SUCCESS_COUNT); // TODO

    case RID_EW_TX_FAILCOUNT:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_i32(ctx, EW_TX_FAILCOUNT); // TODO

    case RID_EW_TX_RETRY_COUNT:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_i32(ctx, EW_TX_RETRY_COUNT); // TODO

    case RID_EW_RSSI:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_i32(ctx, EW_RSSI); // TODO

    case RID_EW_INTERVALO_DE_ENVIO:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_i32(ctx, EW_INTERVALO_DE_ENVIO); // TODO

    case RID_PARENT_IPV6_PREFERRED:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_string(ctx, PARENT_IPV6_PREFERRED); // TODO

    case RID_PARENT_IPV6_ALTERNATIVE:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_string(ctx, PARENT_IPV6_ALTERNATIVE); // TODO

    case RID_TIME_TO_CONNECT:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_i32(ctx, TIME_TO_CONNECT); // TODO

    default:
        return ANJAY_ERR_METHOD_NOT_ALLOWED;
    }
}

static const anjay_dm_object_def_t OBJ_DEF = {
    .oid = 32770,
    .handlers = {
        .list_instances = anjay_dm_list_instances_SINGLE,

        .list_resources = list_resources,
        .resource_read = resource_read,

        // TODO: implement these if transactional write/create is required
        .transaction_begin = anjay_dm_transaction_NOOP,
        .transaction_validate = anjay_dm_transaction_NOOP,
        .transaction_commit = anjay_dm_transaction_NOOP,
        .transaction_rollback = anjay_dm_transaction_NOOP
    }
};

const anjay_dm_object_def_t **diagnostico_wi_sun_object_create(void) {
    diagnostico_wi_sun_object_t *obj = (diagnostico_wi_sun_object_t *) avs_calloc(1, sizeof(diagnostico_wi_sun_object_t));
    if (!obj) {
        return NULL;
    }
    obj->def = &OBJ_DEF;

    // TODO: object init

    return &obj->def;
}

void diagnostico_wi_sun_object_release(const anjay_dm_object_def_t **def) {
    if (def) {
        diagnostico_wi_sun_object_t *obj = get_obj(def);

        // TODO: object cleanup

        avs_free(obj);
    }
}
